package suppressionreason

// What each rule of an umbrella linter reports, used when a reason names the rule it answers.
// Every description is the rule's own title from the linter's documentation, with only what a
// structural fact cannot hold taken out: backticks and quotes dropped, contractions written out, a
// trailing question or a second sentence cut, and a code operator such as "n == 0" spelled in
// words. A rule whose title still cannot be sent as a fact is left out, and so is an ID that has
// meant two things across releases; a reason naming either is unsupported.

// gosecRules is the rules list of gosec v2.28.0 (RULES.md). G113 and G307 were reassigned to new
// checks, so a reason that names them may mean the old one; they are left out.
var gosecRules = map[string]string{
	"G101": "Look for hardcoded credentials",
	"G102": "Bind to all interfaces",
	"G103": "Audit the use of unsafe block",
	"G104": "Audit errors not checked",
	"G106": "Audit the use of ssh.InsecureIgnoreHostKey function",
	"G107": "URL provided to HTTP request as taint input",
	"G108": "Profiling endpoint is automatically exposed",
	"G109": "Converting strconv.Atoi result to int32/int16",
	"G110": "Detect io.Copy instead of io.CopyN when decompressing",
	"G111": "Detect http.Dir with the root directory as a potential risk",
	"G112": "Detect ReadHeaderTimeout not configured as a potential risk",
	"G114": "Use of net/http serve function that has no support for setting timeouts",
	"G115": "Type conversion which leads to integer overflow",
	"G116": "Detect Trojan Source attacks using bidirectional Unicode characters",
	"G117": "Potential exposure of secrets via JSON/YAML/XML/TOML marshaling",
	"G118": "Context propagation failure leading to goroutine/resource leaks",
	"G119": "Unsafe redirect policy may propagate sensitive headers",
	"G120": "Unbounded ParseMultipartForm in HTTP handlers can cause memory exhaustion",
	"G121": "Unsafe CrossOriginProtection bypass patterns",
	"G122": "Filesystem TOCTOU race risk in filepath.Walk/WalkDir callbacks",
	"G123": "TLS resumption may bypass VerifyPeerCertificate when VerifyConnection is unset",
	"G124": "Insecure HTTP cookie configuration missing Secure, HttpOnly, or SameSite attributes",
	"G201": "SQL query construction using format string",
	"G202": "SQL query construction using string concatenation",
	"G203": "Use of unescaped data in HTML templates",
	"G204": "Audit use of command execution",
	"G301": "Poor file permissions used when creating a directory",
	"G302": "Poor file permissions used when creating file or using chmod",
	"G303": "Creating tempfile using a predictable path",
	"G304": "File path provided as taint input",
	"G305": "File path traversal when extracting zip archive",
	"G306": "Poor file permissions used when writing to a file",
	"G401": "Detect the usage of MD5 or SHA1",
	"G402": "Look for bad TLS connection settings",
	"G403": "Ensure minimum RSA key length of 2048 bits",
	"G404": "Insecure random number source (rand)",
	"G405": "Detect the usage of DES or RC4",
	"G406": "Detect the usage of deprecated MD4 or RIPEMD160",
	"G407": "Use of hardcoded IV/nonce for encryption",
	"G408": "Stateful misuse of ssh.PublicKeyCallback leading to auth bypass",
	"G501": "Import blocklist, crypto/md5",
	"G502": "Import blocklist, crypto/des",
	"G503": "Import blocklist, crypto/rc4",
	"G504": "Import blocklist, net/http/cgi",
	"G505": "Import blocklist, crypto/sha1",
	"G506": "Import blocklist, golang.org/x/crypto/md4",
	"G507": "Import blocklist, golang.org/x/crypto/ripemd160",
	"G601": "Implicit memory aliasing in RangeStmt (Go 1.21 or lower)",
	"G602": "Possible slice bounds out of range",
	"G701": "SQL injection via taint analysis",
	"G702": "Command injection via taint analysis",
	"G703": "Path traversal via taint analysis",
	"G704": "SSRF via taint analysis",
	"G705": "XSS via taint analysis",
	"G706": "Log injection via taint analysis",
	"G707": "SMTP command/header injection via taint analysis",
	"G708": "Server-side template injection via text/template",
	"G709": "Unsafe deserialization of untrusted data",
	"G710": "Open redirect via taint analysis",
}

// staticcheckRules are the check titles of staticcheck v0.8.0 (honnef.co/go/tools): SA, S, ST and QF.
var staticcheckRules = map[string]string{
	"SA1000": "Invalid regular expression",
	"SA1001": "Invalid template",
	"SA1002": "Invalid format in time.Parse",
	"SA1003": "Unsupported argument to functions in encoding/binary",
	"SA1004": "Suspiciously small untyped constant in time.Sleep",
	"SA1005": "Invalid first argument to exec.Command",
	"SA1006": "Printf with dynamic first argument and no further arguments",
	"SA1007": "Invalid URL in net/url.Parse",
	"SA1008": "Non-canonical key in http.Header map",
	"SA1010": "regexp.Regexp.FindAll called with n set to 0, which will always return zero results",
	"SA1011": "Various methods in the strings package expect valid UTF-8, but invalid input is provided",
	"SA1012": "A nil context.Context is being passed to a function, consider using context.TODO instead",
	"SA1013": "io.Seeker.Seek is being called with the whence constant as the first argument, but it should be the second",
	"SA1014": "Non-pointer value passed to Unmarshal or Decode",
	"SA1015": "Using time.Tick in a way that will leak",
	"SA1016": "Trapping a signal that cannot be trapped",
	"SA1017": "Channels used with os/signal.Notify should be buffered",
	"SA1018": "strings.Replace called with n set to 0, which does nothing",
	"SA1019": "Using a deprecated function, variable, constant or field",
	"SA1020": "Using an invalid host and port pair with a net.Listen-related function",
	"SA1021": "Using bytes.Equal to compare two net.IP",
	"SA1023": "Modifying the buffer in an io.Writer implementation",
	"SA1024": "A string cutset contains duplicate characters",
	"SA1025": "It is not possible to use the return value of time.Timer.Reset correctly",
	"SA1026": "Cannot marshal channels or functions",
	"SA1027": "Atomic access to 64-bit variable must be 64-bit aligned",
	"SA1028": "sort.Slice can only be used on slices",
	"SA1029": "Inappropriate key in call to context.WithValue",
	"SA1030": "Invalid argument in call to a strconv function",
	"SA1031": "Overlapping byte slices passed to an encoder",
	"SA1032": "Wrong order of arguments to errors.Is",
	"SA2000": "sync.WaitGroup.Add called inside the goroutine, leading to a race condition",
	"SA2001": "Empty critical section",
	"SA2002": "Called testing.T.FailNow or SkipNow in a goroutine, which is not allowed",
	"SA2003": "Deferred Lock right after locking, likely meant to defer Unlock instead",
	"SA3000": "TestMain does not call os.Exit, hiding test failures",
	"SA3001": "Assigning to b.N in benchmarks distorts the results",
	"SA4000": "Binary operator has identical expressions on both sides",
	"SA4003": "Comparing unsigned values against negative values is pointless",
	"SA4004": "The loop exits unconditionally after one iteration",
	"SA4005": "Field assignment that will never be observed",
	"SA4006": "A value assigned to a variable is never read before being overwritten",
	"SA4008": "The variable in the loop condition never changes",
	"SA4009": "A function argument is overwritten before its first use",
	"SA4010": "The result of append will never be observed anywhere",
	"SA4011": "Break statement with no effect",
	"SA4012": "Comparing a value against NaN even though no value is equal to NaN",
	"SA4014": "An if/else if chain has repeated conditions and no side-effects",
	"SA4015": "Calling functions like math.Ceil on floats converted from integers does not do anything useful",
	"SA4017": "Discarding the return values of a function without side effects, making the call pointless",
	"SA4018": "Self-assignment of variables",
	"SA4019": "Multiple, identical build constraints in the same file",
	"SA4020": "Unreachable case clause in a type switch",
	"SA4022": "Comparing the address of a variable against nil",
	"SA4023": "Impossible comparison of interface value with untyped nil",
	"SA4024": "Checking for impossible return value from a builtin function",
	"SA4025": "Integer division of literals that results in zero",
	"SA4026": "Go constants cannot express negative zero",
	"SA4027": "net/url.URL.Query returns a copy, modifying it does not change the URL",
	"SA4029": "Ineffective attempt at sorting slice",
	"SA4030": "Ineffective attempt at generating random number",
	"SA4031": "Checking never-nil value against nil",
	"SA4032": "Comparing runtime.GOOS or runtime.GOARCH against impossible value",
	"SA5000": "Assignment to nil map",
	"SA5001": "Deferring Close before checking for a possible error",
	"SA5002": "The empty for loop spins and can block the scheduler",
	"SA5003": "Defers in infinite loops will never execute",
	"SA5005": "The finalizer references the finalized object, preventing garbage collection",
	"SA5007": "Infinite recursive call",
	"SA5008": "Invalid struct tag",
	"SA5009": "Invalid Printf call",
	"SA5010": "Impossible type assertion",
	"SA5011": "Possible nil pointer dereference",
	"SA5012": "Passing odd-sized slice to function expecting even size",
	"SA6000": "Using regexp.Match or related in a loop, should use regexp.Compile",
	"SA6001": "Missing an optimization opportunity when indexing maps by byte slices",
	"SA6002": "Storing non-pointer values in sync.Pool allocates memory",
	"SA6003": "Converting a string to a slice of runes before ranging over it",
	"SA6005": "Inefficient string comparison with strings.ToLower or strings.ToUpper",
	"SA9001": "Defers in range loops may not run when you expect them to",
	"SA9002": "Using a non-octal os.FileMode that looks like it was meant to be in octal",
	"SA9003": "Empty body in an if or else branch",
	"SA9004": "Only the first constant has an explicit type",
	"SA9005": "Trying to marshal a struct with no public fields nor custom marshaling",
	"SA9006": "Dubious bit shifting of a fixed size integer value",
	"SA9007": "Deleting a directory that should not be deleted",
	"SA9008": "else branch of a type assertion is probably not reading the right value",
	"SA9009": "Ineffectual Go compiler directive",
	"SA9010": "Returned function should be called in defer",
	"S1000":  "Use plain channel send or receive instead of single-case select",
	"S1001":  "Replace for loop with call to copy",
	"S1002":  "Omit comparison with boolean constant",
	"S1003":  "Replace call to strings.Index with strings.Contains",
	"S1004":  "Replace call to bytes.Compare with bytes.Equal",
	"S1005":  "Drop unnecessary use of the blank identifier",
	"S1007":  "Simplify regular expression by using raw string literal",
	"S1008":  "Simplify returning boolean expression",
	"S1009":  "Omit redundant nil check on slices, maps, and channels",
	"S1010":  "Omit default slice index",
	"S1011":  "Use a single append to concatenate two slices",
	"S1012":  "Replace time.Now().Sub(x) with time.Since(x)",
	"S1016":  "Use a type conversion instead of manually copying struct fields",
	"S1017":  "Replace manual trimming with strings.TrimPrefix",
	"S1018":  "Use copy for sliding elements",
	"S1019":  "Simplify make call by omitting redundant arguments",
	"S1020":  "Omit redundant nil check in type assertion",
	"S1021":  "Merge variable declaration and assignment",
	"S1023":  "Omit redundant control flow",
	"S1024":  "Replace x.Sub(time.Now()) with time.Until(x)",
	"S1028":  "Simplify error construction with fmt.Errorf",
	"S1029":  "Range over the string directly",
	"S1030":  "Use bytes.Buffer.String or bytes.Buffer.Bytes",
	"S1031":  "Omit redundant nil check around loop",
	"S1032":  "Use sort.Ints(x), sort.Float64s(x), and sort.Strings(x)",
	"S1033":  "Unnecessary guard around call to delete",
	"S1034":  "Use result of type assertion to simplify cases",
	"S1035":  "Redundant call to net/http.CanonicalHeaderKey in method call on net/http.Header",
	"S1036":  "Unnecessary guard around map access",
	"S1037":  "Elaborate way of sleeping",
	"S1038":  "Unnecessarily complex way of printing formatted string",
	"S1039":  "Unnecessary use of fmt.Sprint",
	"S1040":  "Type assertion to current type",
	"ST1000": "Incorrect or missing package comment",
	"ST1001": "Dot imports are discouraged",
	"ST1003": "Poorly chosen identifier",
	"ST1005": "Incorrectly formatted error string",
	"ST1006": "Poorly chosen receiver name",
	"ST1008": "The error value of a function should be its last return value",
	"ST1011": "Poorly chosen name for variable of type time.Duration",
	"ST1012": "Poorly chosen name for error variable",
	"ST1013": "Should use constants for HTTP error codes, not magic numbers",
	"ST1015": "The default case of a switch should be the first or last case",
	"ST1016": "Use consistent method receiver names",
	"ST1017": "Do not use Yoda conditions",
	"ST1018": "Avoid zero-width and control characters in string literals",
	"ST1019": "Importing the same package multiple times",
	"ST1020": "The documentation of an exported function should start with the name of the function",
	"ST1021": "The documentation of an exported type should start with the name of the type",
	"ST1022": "The documentation of an exported variable or constant should start with the name of the variable",
	"QF1001": "Apply De Morgan law",
	"QF1002": "Convert untagged switch to tagged switch",
	"QF1003": "Convert if/else-if chain to tagged switch",
	"QF1005": "Expand call to math.Pow",
	"QF1006": "Lift if and break into loop condition",
	"QF1007": "Merge conditional assignment into variable declaration",
	"QF1008": "Omit embedded fields from selector expression",
	"QF1010": "Convert slice of bytes to string when printing it",
	"QF1012": "Use fmt.Fprintf(x, ...) instead of x.Write(fmt.Sprintf(...))",
}

// reviveRules are the rule descriptions of the rules table in the revive v1.15.0 README.
var reviveRules = map[string]string{
	"add-constant":                    "Suggests using constant for magic numbers and string literals",
	"argument-limit":                  "Specifies the maximum number of arguments a function can receive",
	"atomic":                          "Check for common mistaken usages of the sync/atomic package",
	"banned-characters":               "Checks banned characters in identifiers",
	"bare-return":                     "Warns on bare returns",
	"blank-imports":                   "Disallows blank imports",
	"bool-literal-in-expr":            "Suggests removing Boolean literals from logic expressions",
	"call-to-gc":                      "Warns on explicit call to the garbage collector",
	"cognitive-complexity":            "Sets restriction for maximum Cognitive complexity",
	"comment-spacings":                "Warns on malformed comments",
	"comments-density":                "Enforces a minimum comment / code relation",
	"confusing-naming":                "Warns on methods with names that differ only by capitalization",
	"confusing-results":               "Suggests to name potentially confusing function results",
	"constant-logical-expr":           "Warns on constant logical expressions",
	"context-as-argument":             "context.Context should be the first argument of a function",
	"context-keys-type":               "Disallows the usage of basic types in context.WithValue",
	"cyclomatic":                      "Sets restriction for maximum Cyclomatic complexity",
	"datarace":                        "Spots potential dataraces",
	"deep-exit":                       "Looks for program exits in funcs other than main() or init()",
	"defer":                           "Warns on some defer gotchas",
	"dot-imports":                     "Forbids . imports",
	"duplicated-imports":              "Looks for packages that are imported two or more times",
	"early-return":                    "Spots if-then-else statements where the predicate may be inverted to reduce nesting",
	"empty-block":                     "Warns on empty code blocks",
	"empty-lines":                     "Warns when there are heading or trailing newlines in a block",
	"enforce-repeated-arg-type-style": "Enforces consistent style for repeated argument and/or return value types",
	"enforce-switch-style":            "Enforces consistent usage of default on switch statements",
	"epoch-naming":                    "Enforces naming conventions for epoch time variables",
	"error-naming":                    "Naming of error variables",
	"error-return":                    "The error return parameter should be last",
	"error-strings":                   "Conventions around error strings",
	"errorf":                          "Should replace errors.New(fmt.Sprintf()) with fmt.Errorf()",
	"exported":                        "Naming and commenting conventions on exported symbols",
	"file-header":                     "Header which each file should have",
	"file-length-limit":               "Enforces a maximum number of lines per file",
	"filename-format":                 "Enforces the formatting of filenames",
	"flag-parameter":                  "Warns on boolean parameters that create a control coupling",
	"forbidden-call-in-wg-go":         "Warns on forbidden calls inside calls to wg.Go",
	"function-length":                 "Warns on functions exceeding the statements or lines max",
	"function-result-limit":           "Specifies the maximum number of results a function can return",
	"get-return":                      "Warns on getters that do not yield any result",
	"identical-branches":              "Spots if-then-else statements with identical then and else branches",
	"identical-ifelseif-branches":     "Spots if ... else if chains with identical branches",
	"identical-ifelseif-conditions":   "Spots identical conditions in  if ... else if chains",
	"identical-switch-branches":       "Spots switch with identical branches",
	"identical-switch-conditions":     "Spots identical conditions in case clauses of switch statements",
	"if-return":                       "Redundant if when returning an error",
	"import-alias-naming":             "Conventions around the naming of import aliases",
	"import-shadowing":                "Spots identifiers that shadow an import",
	"imports-blocklist":               "Disallows importing the specified packages",
	"indent-error-flow":               "Prevents redundant else statements",
	"inefficient-map-lookup":          "Spots iterative searches for a key in a map",
	"line-length-limit":               "Specifies the maximum number of characters in a line",
	"max-control-nesting":             "Sets restriction for maximum nesting of control structures",
	"max-public-structs":              "The maximum number of public structs in a file",
	"modifies-parameter":              "Warns on assignments to function parameters",
	"modifies-value-receiver":         "Warns on assignments to value-passed method receivers",
	"nested-structs":                  "Warns on structs within structs",
	"optimize-operands-order":         "Checks inefficient conditional expressions",
	"package-comments":                "Package commenting conventions",
	"package-directory-mismatch":      "Checks that package name matches containing directory name",
	"package-naming":                  "Checks that package names follow Go conventions and best practices",
	"range":                           "Prevents redundant variables when iterating over a collection",
	"range-val-address":               "Warns if address of range value is used dangerously",
	"range-val-in-closure":            "Warns if range value is used in a closure dispatched as goroutine",
	"receiver-naming":                 "Conventions around the naming of receivers",
	"redefines-builtin-id":            "Warns on redefinitions of builtin identifiers",
	"redundant-import-alias":          "Warns on import aliases matching the imported package name",
	"redundant-test-main-exit":        "Suggests removing Exit call in TestMain function for test files",
	"string-format":                   "Warns on specific string literals that fail one or more user-configured regular expressions",
	"string-of-int":                   "Warns on suspicious casts from int to string",
	"struct-tag":                      "Checks common struct tags like json, xml, yaml",
	"superfluous-else":                "Prevents redundant else statements (extends indent-error-flow)",
	"time-date":                       "Reports bad usage of time.Date",
	"time-naming":                     "Conventions around the naming of time variables",
	"unchecked-type-assertion":        "Disallows type assertions without checking the result",
	"unconditional-recursion":         "Warns on function calls that will lead to (direct) infinite recursion",
	"unexported-naming":               "Warns on wrongly named un-exported symbols",
	"unexported-return":               "Warns when a public return is from unexported type",
	"unhandled-error":                 "Warns on unhandled errors returned by function calls",
	"unnecessary-format":              "Identifies calls to formatting functions where the format string does not contain any formatting verbs",
	"unnecessary-if":                  "Identifies if-else statements that can be replaced by simpler statements",
	"unnecessary-stmt":                "Suggests removing or simplifying unnecessary statements",
	"unreachable-code":                "Warns on unreachable code",
	"unsecure-url-scheme":             "Checks for usage of potentially unsecure URL schemes",
	"unused-parameter":                "Suggests to rename or remove unused function parameters",
	"unused-receiver":                 "Suggests to rename or remove unused method receivers",
	"use-errors-new":                  "Spots calls to fmt.Errorf that can be replaced by errors.New",
	"use-fmt-print":                   "Proposes to replace calls to built-in print and println with their equivalents from fmt",
	"use-slices-sort":                 "Proposes to replace calls to sort.Ints, sort.Strings and the like with their equivalents from slices package",
	"useless-break":                   "Warns on useless break statements in case clauses",
	"useless-fallthrough":             "Warns on useless fallthrough statements in case clauses",
	"var-declaration":                 "Reduces redundancies around variable declaration",
	"var-naming":                      "Naming rules",
	"waitgroup-by-value":              "Warns on functions taking sync.WaitGroup as a by-value parameter",
}

// reviveUndescribed are the revive v1.15.0 rules whose README description cannot be sent as a fact.
// A reason that cites one is unsupported, not read as prose against the general description.
var reviveUndescribed = map[string]bool{
	"enforce-map-style":   true,
	"enforce-slice-style": true,
	"increment-decrement": true,
	"redundant-build-tag": true,
	"time-equal":          true,
	"use-any":             true,
	"use-waitgroup-go":    true,
}
