package cli_test

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// Regressions from the M1 review: each test is one reproduction from it.

func appendConfig(t *testing.T, dir, extra string) {
	t.Helper()
	p := filepath.Join(dir, ".lintuition.yml")
	b, err := os.ReadFile(p)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(p, append(b, []byte(extra)...), 0o600); err != nil {
		t.Fatal(err)
	}
}

func TestGeneratedOutsideBase(t *testing.T) {
	dir := sample(t)
	p := filepath.Join(dir, "metrics.go")
	b, _ := os.ReadFile(p)
	os.WriteFile(p, append([]byte("// Code generated by review. DO NOT EDIT.\n\n"), b...), 0o600)
	for _, wd := range []string{dir, filepath.Join(dir, "sub")} {
		os.MkdirAll(wd, 0o700)
		t.Chdir(wd)
		pattern := "./..."
		if wd != dir {
			pattern = "../"
		}
		if code, _, errs := run("run", pattern); code != 0 || !strings.Contains(errs, "0 asked") || !strings.Contains(errs, "4 skipped") {
			t.Fatalf("from %s: exit %d, %s", wd, code, errs)
		}
	}
}

func TestRelativeConfigPathCfgMode(t *testing.T) {
	dir := sample(t)
	appendConfig(t, dir, "run:\n  relative-path-mode: cfg\n")
	os.MkdirAll(filepath.Join(dir, "sub"), 0o700)
	for _, cfg := range []string{"../.lintuition.yml", filepath.Join(dir, ".lintuition.yml")} {
		t.Chdir(filepath.Join(dir, "sub"))
		_, out, errs := run("run", "-c", cfg, "--output.json.path", "stdout", "../")
		var rep struct {
			Issues []struct{ Pos struct{ Filename string } }
		}
		if err := json.Unmarshal([]byte(out), &rep); err != nil || len(rep.Issues) != 1 || rep.Issues[0].Pos.Filename != "metrics.go" {
			t.Fatalf("-c %s: %v %s %s", cfg, err, out, errs)
		}
	}
}

func TestOutputOptions(t *testing.T) {
	dir := sample(t)
	appendConfig(t, dir, "output:\n  show-stats: false\n")
	if code, _, errs := run("run", "./..."); code != 1 || errs != "" {
		t.Fatalf("show-stats false: exit %d, stderr %q", code, errs)
	}
	for _, key := range []string{"output:\n  sort-order: [file]\n", "run:\n  concurrency: 4\n", "output:\n  formats:\n    text:\n      colors: true\n"} {
		os.WriteFile(filepath.Join(dir, ".lintuition.yml"), []byte("version: \"2\"\n"+key), 0o600)
		if code, _, errs := run("config", "verify"); code != 2 || !strings.Contains(errs, "not found") {
			t.Fatalf("%q must be rejected until implemented: exit %d %s", key, code, errs)
		}
	}
}

func TestDisabledLinterSettingsValidated(t *testing.T) {
	dir := sample(t)
	for _, body := range []string{
		"version: \"2\"\nlinters:\n  default: none\n  settings:\n    metric-type-vs-help:\n      thershold: 5\n",
		"version: \"2\"\nlinters:\n  default: none\n  settings:\n    metric-type-vs-help:\n      threshold: 5\n",
	} {
		os.WriteFile(filepath.Join(dir, ".lintuition.yml"), []byte(body), 0o600)
		if code, _, errs := run("config", "verify"); code != 2 || !strings.Contains(errs, "metric-type-vs-help") {
			t.Fatalf("%q: exit %d %s", body, code, errs)
		}
	}
}

func TestSecondYAMLDocumentRejected(t *testing.T) {
	dir := sample(t)
	appendConfig(t, dir, "---\nsemantic: {payload: facts, local-only: true}\n")
	if code, _, errs := run("run", "./..."); code != 2 || !strings.Contains(errs, "only one YAML document") {
		t.Fatalf("exit %d %s", code, errs)
	}
}

func TestOutputDestinations(t *testing.T) {
	sample(t)
	for _, args := range [][]string{
		{"--output.text.path", "stdout", "--output.json.path", "stdout"},
		{"--output.json.path", "stderr"},
		{"--output.text.path", "out.txt", "--output.json.path", "./out.txt"},
	} {
		code, out, errs := run(append(append([]string{"run"}, args...), "./...")...)
		if code != 2 || out != "" || !strings.Contains(errs, "output.formats") {
			t.Fatalf("%v: exit %d, out %q, %s", args, code, out, errs)
		}
	}
}

func TestNaNRejected(t *testing.T) {
	dir := sample(t)
	for _, extra := range []string{
		"linters:\n  settings:\n    metric-type-vs-help:\n      threshold: .nan\n",
		"linters:\n  settings:\n    metric-type-vs-help:\n      threshold: .inf\n",
	} {
		os.WriteFile(filepath.Join(dir, "nan.yml"), []byte("version: \"2\"\n"+extra), 0o600)
		if code, _, errs := run("config", "verify", "-c", "nan.yml"); code != 2 || !strings.Contains(errs, "must be a number in (0, 1]") {
			t.Fatalf("%q: exit %d %s", extra, code, errs)
		}
	}
	os.WriteFile(filepath.Join(dir, "nan.yml"), []byte("version: \"2\"\nsemantic:\n  budget:\n    max-cost-usd: .nan\n"), 0o600)
	if code, _, errs := run("config", "verify", "-c", "nan.yml"); code != 2 || !strings.Contains(errs, "finite") {
		t.Fatalf("NaN budget: exit %d %s", code, errs)
	}
}

func TestEmptyPackageMatchIsIncomplete(t *testing.T) {
	dir := sample(t)
	os.MkdirAll(filepath.Join(dir, "empty"), 0o700)
	if code, _, errs := run("run", "./empty/..."); code != 2 || !strings.Contains(errs, "no packages matched") {
		t.Fatalf("exit %d %s", code, errs)
	}
}
