package engine

import (
	"go/ast"
	"go/parser"
	"go/token"
	"strings"
	"time"

	"github.com/ssgreg/lintuition/internal/config"
)

// isGenerated applies linters.exclusions.generated: strict honours only the standard
// "Code generated ... DO NOT EDIT." header, lax also the common looser markers, disable none.
func isGenerated(c *config.Config, cache map[string]bool, path string) bool {
	mode := c.Linters.Exclusions.Generated
	if mode == "disable" {
		return false
	}
	if v, ok := cache[path]; ok {
		return v
	}
	f, err := parser.ParseFile(token.NewFileSet(), path, nil, parser.ParseComments|parser.PackageClauseOnly)
	v := false
	if err == nil {
		v = ast.IsGenerated(f)
		if !v && mode == "lax" {
			for _, cg := range f.Comments {
				t := strings.ToLower(cg.Text())
				if strings.Contains(t, "do not edit") || strings.Contains(t, "autogenerated file") || strings.Contains(t, "automatically generated") {
					v = true
					break
				}
			}
		}
	}
	cache[path] = v
	return v
}

func timeDuration(d config.Duration) time.Duration { return time.Duration(d) }
